language: python

python:
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
fail_fast: true

before_install:
  - which python; python --version
  - pip install -r requirements-test.txt
  # Stop the build if it doesn't pass syntax and complexity checks
  - flake8 . --count --show-source --max-complexity=8 --statistics

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest

script:
  - pytest --cov autocrop -v --cov-report term-missing

after_success:
  - codecov
