environment:

  matrix:

    # For Python versions available on AppVeyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r requirements-dev.txt"
  - "%PYTHON%\\python.exe -m flake8 . --count --show-source --max-complexity=10 --statistics"
  - "%PYTHON%\\python.exe -m pip install ."

build: false

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  # - "build.cmd %PYTHON%\\python.exe setup.py test"
  - "%PYTHON%\\python.exe -m pytest --cov autocrop -v --cov-report term-missing"

